export const BEERS_FETCH = 'BEERS_FETCH';
export const CLEAR_BEERS_CACHE = 'CLEAR_BEERS_CACHE';

export const PAGE_CHANGE = 'PAGE_CHANGE';
export const PAGE_RESET = 'PAGE_RESET';

export const SORT_CHANGE = 'SORT_CHANGE';

export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';

export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_HIDE = 'ERROR_HIDE';

export const CART_FETCH_ITEMS = 'CART_FETCH_ITEMS';
export const CART_CLEAR_CACHE = 'CART_CLEAR_CACHE';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';

export const FAVORITE_ADD = 'FAVORITE_ADD';
export const FAVORITES_LOAD = 'FAVORITES_LOAD';
export const FAVORITE_REMOVE = 'FAVORITE_REMOVE';
export const FAVORITES_FETCH = 'FAVORITES_FETCH';
